version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/dependency
      runas: root
    - location: scripts/start_app
      timeout: 180
      runas: root
        
  ApplicationStart:
    - location: scripts/stop_app
      timeout: 360
      runas: root
